stages:
  preprocess_data:
    cmd: python src/preprocess_data.py
    deps:
    - src/preprocess_data.py 
    - data/raw/lgg-mri-segmentation
    outs:
    - data/preprocessed/train.csv
    - data/preprocessed/valid.csv
    - data/preprocessed/test.csv