base:
  project: Brain MRI segmentation
  random_state: 42

dataset:
  raw_dataset: data/raw/lgg-mri-segmentation
  train_csv: data/preprocessed/train.csv
  eval_csv: data/preprocessed/eval.csv
  mean: [-0.8993, -0.8798, -0.8943]
  std: [0.0039, 0.0039, 0.0040]
  image_height: 256
  image_width: 256
  batch_size: 32
  num_workers: 2

model:
  in_channels: 3
  out_channels: 1

train:
  lr: 3e-4
  num_epochs: 10
  checkpoint_path: './saved_models/unet.pth.tar'
  load_checkpoint: False